# Generated by Django 4.2.11 on 2024-11-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField()),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField()),
                ('title', models.TextField()),
                ('rank', models.FloatField()),
                ('release_date', models.DateField()),
                ('summary', models.TextField()),
                ('poster_path', models.TextField()),
                ('is_adult', models.BooleanField()),
            ],
        ),
    ]
